import { Audio } from '../../Themes';
import {Images} from '../../Themes';
export const barcelonaParcGuell = [
    {
      id: "1",
      title: "Who was Antoni Gaudi?",
      length: 32, 
      date: "Feb 2021", 
      tags: ["History", "Art", "Architecture"],
      author: "author",
      transcript: `insert a transcript`,
      image: Images.oasis,
      audio: Audio.oasis,
    },
    {
      id: "2",
      title: "The History of Parc Guëll",
      length: 19, 
      date: "Dec 2020", 
      tags: ["History", "Architecture"],
      author: "author",
      transcript: `insert a transcript`,
      image: Images.oasis,
      audio: Audio.oasis,
    },
    {
      id: "3",
      title: "A Haven Amidst the Chaos",
      length: 28, 
      date: "Nov 2020", 
      tags: ["Heart-Warmer", "Community"],
      author: "author",
      transcript: `insert a transcript`,
      image: Images.oasis,
      audio: Audio.oasis,
    },
    {
    id: "4",
    title: "Parc Guëll under Covid",
    length: 31, 
    date: "Mar 2019", 
    tags: ["COVID-19", "Music", "Love"],
    author: "author",
    transcript: `insert a transcript`,
    image: Images.oasis,
    audio: Audio.oasis,
    },
    {
    id: "5",
    title: "A Local Perspective on Our Park",
    length: 8, 
    date: "Jan 2019", 
    tags: ["History", "Community", "Love"],
    author: "author",
    transcript: `insert a transcript`,
    image: Images.oasis,
    audio: Audio.oasis,
    },
    {
    id: "6",
    title: "Picnics at Parc Guëll",
    length: 24, 
    date: "May 2018", 
    tags: ["Food", "Family", "Community"],
    author: "author",
    transcript: `insert a transcript`,
    image: Images.oasis,
    audio: Audio.oasis,
    },
    {
    id: "7",
    title: "The Ghost of Gaudi",
    length: 52, 
    date: "Mar 2018", 
    tags: ["Folklore", "History", "Community"],
    author: "author",
    transcript: `insert a transcript`,
    image: Images.oasis,
    audio: Audio.oasis,
    },
    
    {
    id: "8",
    title: "Hidden Secrets of the Park",
    length: 21, 
    date: "Jan 2018", 
    tags: ["Folklore", "Community"],
    author: "author",
    transcript: `insert a transcript`,
    image: Images.oasis,
    audio: Audio.oasis,
    },
    {
    id: "9",
    title: "What it means to be a UNESCO Site",
    length: 18, 
    date: "Dec 2017", 
    tags: ["History", "Community"], 
    author: "author",
    transcript: `insert a transcript`,
    image: Images.oasis,
    audio: Audio.oasis,
    }
];
