import {Images} from '../../Themes';
import images from '../../Themes/Images';
import { Audio } from '../../Themes';

export const barcelonaCascadaStories = [
    {
      locationIndex: 2,
      title: "An Oasis Amidst Uncertainty",
      length: 1, 
      date: "Oct 2020", 
      tags: ["COVID-19", "Art", "Outdoors"],
      author: "vmiller",
      image: Images.cascada,
      audio: Audio.oasis,
      transcript: `2020 has been a hard year for everyone. During the shutdowns and closures, parc de la ciutadella has become an oasis for Barcelona’s locals. In normal times, the park is crowded with tourists exploring our beautiful city. But since the shutdowns, more locals than ever have come to enjoy spending time in the park. I personally like to sit by la Cascada and write. The serenity of the atmosphere allows me to create my best work.`,
    },
    {
      locationIndex: 2,
      title: "Why the Government Blocked Access to Our Park",
      length: 2, 
      date: "Jul 2020", 
      tags: ["Politics", "Protest"],
      image: Images.blockedCasc,
      audio: Audio.blockedAccess,
      author: "vmiller",
      transcript: `Parc de la cittadella has become an important symbolic place in the political movement for Catalan independence. As a broad public space, it provides ample space for demonstrations and protests. Secessionists and anti-Secessionists alike have taken to the park to make their voices heard. Last week, though, tensions got particularly high. Clashes between the two groups caused the government to shutdown the park entirely, preventing our voices from being heard. `,
    },
    {
      locationIndex: 2,
      title: "The Making of La Cascada",
      length: 2, 
      date: "Feb 2020", 
      tags: ["Art", "Architecture", "History"],
      image: Images.oldImageCitudella,
      audio: Audio.makingOfLaCascada,
      author: "vmiller",
      transcript: `If you are an art and architecture buff like me, you might be interested in the making of La Cascada. All of the wonderful sculpture you see was not initially part of the fountain. It was actually part of a revamp designed to impress at the 1888 Barcelona Universal Exhibition. Designed by Josep Fontsere and allegedly also Antoni Gaudi, it was inspired loosely by Rome’s Trevi Fountain. You can see the greco-roman influence in both the marble sculpture work technique and in the subject choice. The fountain’s centerpiece, Venus standing on an open clam with arms overhead, is a triumphant and bold twist on the Birth of Venus motif, which was famously painted by Sandro Botticelli. `,
    },
    // {
    //     title: "The Locals' Palace",
    //     locationIndex: 2,
    //     length: 31, 
    //     date: "Dec 2019", 
    //     tags: ["Art", "History", "Community"],
    //     author: "author",
    //     transcript: `insert a transcript`,
    //     image: Images.oasis,
    //     audio: Audio.oasis,
    // },
    // {
    //     title: "The Ghost of La Cascada",
    //     locationIndex: 2,
    //     length: 27, 
    //     date: "Oct 2019", 
    //     tags: ["History", "Folklore", "Horror"],
    //     author: "author",
    //     transcript: `insert a transcript`,
    //     image: Images.oasis,
    //     audio: Audio.oasis,
    // },
    // {
    //     title: "Childhood Picnics in La Cascada",
    //     locationIndex: 2,
    //     length: 54, 
    //     date: "Jul 2019", 
    //     tags: ["Heart-Warmer", "Family", "Love"],
    //     author: "author",
    //     transcript: `insert a transcript`,
    //     image: Images.oasis,
    //     audio: Audio.oasis,
    // },
    // {
    //     title: "How La Cascada Saved Us",
    //     locationIndex: 2,
    //     length: 12, 
    //     date: "May 2019", 
    //     tags: ["Heart-Warmer", "Love","Community"],
    //     author: "author",
    //     transcript: `insert a transcript`,
    //     image: Images.oasis,
    //     audio: Audio.oasis,
    // },
    // {
    //     title: "Catalan History of La Cascada",
    //     locationIndex: 2,
    //     length: 49, 
    //     date: "May 2018", 
    //     tags: ["History", "Folktales","Community"],
    //     author: "author",
    //     transcript: `insert a transcript`,
    //     image: Images.oasis,
    //     audio: Audio.oasis,
    // }
];
