import {Images} from '../../Themes';
import { Audio } from '../../Themes';
export const sfBayToBreakers = [
    {
      locationIndex: 8,
      title: "A Tradition Like No Other",
      location: "Bay to Breakers",
      length: 1, 
      date: "May 2019", 
      tags: ["Love", "Community", "Heart Warmer"], 
      author: "tlallas", 
      image: Images.traditionB2B,
      audio: Audio.tradition,
      transcript: `If you’re here in May you might get a chance to see or, if you plan right, to participate in Bay to Breakers. Bay to Breakers is a tradition that screams San Francisco! It has been going on for over 100 years.  This is a 12k like no other. People walk, jog, and dance from Embarcadero to Ocean Beach dressed in wacky costumes. You’ll see groups ranging from the whole game of thrones cast to pac men to donuts. It is a wonderful way to see how San Francisco celebrates life, individuality, and culture!`,
    },
    {
      locationIndex: 8,
      title: "Why I Love Bay to Breakers",
      location: "Bay to Breakers",
      length: 2, 
      date: "May 2019", 
      tags: ["Sports", "Community", "Love"], 
      author: "adrazen", 
      audio: Audio.loveBaytoBreakers,
      image: Images.B2BMarathon,
      transcript: `Every year thousands of Californians come to… Bay to Breakers! This is where I ran my first marathon. I remember that feeling: the rush, the fun, the run. Running at Bay to Breakers is like no other marathon. Not only do you get to run in one of the United States’ greatest cities, you also get to dress up as whatever you want. Every year Bay to Breakers is the heart of San Francisco’s funnest, most exciting race. `,
    },
    {
      locationIndex: 8,
      title: "Bay to Breakers",
      location: "Bay to Breakers",
      length: 5, 
      date: "Oct 2019", 
      tags: ["Sports", "Community", "Journalism"], 
      author: "Total Life Freedom Podcast", 
      audio: Audio.journalistBaytoBreakers,
      image: Images.B2BJournalist,
      transcript: `Alright this is another edition of empty calories. This is a fun story but I"m not sure there is any more to it.`,
    },

    {
      locationIndex: 8,
      title: "Grandbob is Ready for Next Year",
      location: "Bay to Breakers",
      length: 5, 
      date: "May 2020", 
      tags: ["Heart-Warmer", "Community", "Family", "COVID-19"], 
      author: "bsharp", 
      audio: Audio.grandbobB2B,
      image: Images.B2BGrandbob,
      transcript: `Better breakers is known for crazy costumes and people who aren't wearing any costumes or clothing at all, but for me the thing that I remember most fondly about it is doing it almost every year for the last 10 years with my grandfather. I call him grand bob and he is in remarkably good shape for his age and when I mentioned that I thought beta breakers would be fun back when I was 13 or 14 years old he said let's go do that together and so the first year I did it with my grandpa and my dad  And then next year it was just grand bob in me and that's how it's been for the last for most of the times. I've done it. We would never really run but we wouldn't walk too slow either we I remember laughing at the group of people in salmon costumes running the wrong way at the top of Hay Street, I remember. Standing near the embarcadero on one of the random city blocks in our starting gate throwing tortillas as high as I can into the air thinking that that was just one of the most hilarious magical things ever to throw a tortilla up into the air haven't hit an adult in the head he and his four buddies all laugh and they all pick up tortillas and throw them straight back at me. And. While I think maybe at the beginning of this story it sounds like my ambab has passed away he is not he's still doing well. It doesn't look like we're going to be able to do beta breakers this year because of their Corona virus and. This is going to be the first of your that. We have both been in the same place and not run it together. It's better sweet because there are many things that we've missed out on and in the grand scheme of things this is another one and we're all going through it together. But I'm really happy that it looks like I'll be able to do it with Grandpa again next year.`,
    },
];
