import { Audio } from '../../Themes';
import {Images} from '../../Themes';
export const sfMissionDoloresPark = [
    {
      id: "1",
      title: "Mission Dolores: Home of the Ohlone Tribe",
      length: 36, 
      date: "Nov 2020", 
      tags: ["History", "Community"],
      author: "author",
      transcript: `insert a transcript`,
      image: Images.oasis,
      audio: Audio.oasis,
    },
    {
      id: "2",
      title: "The Church and Mission Dolores Park",
      length: 61, 
      date: "Sep 2020", 
      tags: ["Religion", "Community", "Heart-Warmer"],
      author: "author",
      transcript: `insert a transcript`,
      image: Images.oasis,
      audio: Audio.oasis,
    },
    {
      id: "3",
      title: "Reccess at Mission Dolores",
      length: 22, 
      date: "Jul 2020", 
      tags: ["Heart-Warmer", "Community", "Love"],
      author: "author",
      transcript: `insert a transcript`,
      image: Images.oasis,
      audio: Audio.oasis,
    },
    {
      id: "4",
      title: "The Dog Park at Mission Dolores",
      length: 9, 
      date: "May 2020", 
      tags: ["Pets", "Community", "Love"],
      author: "author",
      transcript: `insert a transcript`,
      image: Images.oasis,
      audio: Audio.oasis,
    },
    {
      id: "5",
      title: "Poetry at Mission Dolores",
      length: 12, 
      date: "Jan 2020", 
      tags: ["Art", "Community", "Love"],
      author: "author",
      transcript: `insert a transcript`,
      image: Images.oasis,
      audio: Audio.oasis,
    },
    {
      id: "6",
      title: "My First Music Festival",
      length: 28, 
      date: "Dec 2019", 
      tags: ["Art", "Music", "Love"],
      author: "author",
      transcript: `insert a transcript`,
      image: Images.oasis,
      audio: Audio.oasis,
    },
    {
      id: "7",
      title: "The History of Mission Dolores",
      length: 21, 
      date: "Oct 2019", 
      tags: ["History", "Community", "Love"],
      author: "author",
      transcript: `insert a transcript`,
      image: Images.oasis,
      audio: Audio.oasis,
    }
];
