import {Images} from '../../Themes';
import { Audio } from '../../Themes';
export const sfSmitten = [
    {
       locationIndex: 10,
        title: "Smitten with Smitten",
        location: "Smitten Ice Cream",
        length: 1, 
        date: "Aug 2020", 
        tags: ["Love", "Community"], 
        author: "tlallas", 
        image: Images.smittenWithSmitten,
        audio: Audio.smittenIceCream,
        transcript: `Smitten ice cream isn’t just incredibly tasty— it is an engineering marvel! All of the ice cream is made with the patented ‘Brrr’ machine. The founder of Smitten worked with a team of 14 engineers to create the Brrr machine.  Using a combination of liquid nitrogen and double helical beaters, the Brr machine creates ice cream with the ideal texture, viscosity, and richness. Although you can go to Smitten’s permanent locations in PacHeights, Hayes Valley, Santana Row, and Rockridge, Smitten started out as just the Brr machine on a radio flyer wagon. The founder Robyn Fisher made Smitten a household name, charting her wagon all over the iconic places of SF. Now you can order ice cream from Brrrristas that will be the smoothest, richest ice cream in the bay. I truly cannot live without the cookie dough ice cream with pretzels and chocolate chips. Go try some!`,
      },
      {
        locationIndex: 10,
        title: "Smitten Ice Cream: More than Just Ice Cream",
        location: "Smitten Ice Cream",
        length: 2, 
        date: "April 2019", 
        tags: ["Food", "Heart-Warmer"], 
        author: "adrazen", 
        image: Images.moreThanIceCreamShop,
        audio: Audio.moreThanIceCreamShop,
        transcript: `Nothing screams childhood memories more to me than Smitten Ice Cream. Smitten Ice cream isn’t just any old ice cream shop.When people tell me, “oh yeah, I know about Smitten Ice Cream, it’s like my neighborhood ice cream shop”, I get really offended. Smitten Ice Cream is special more than just about the ice cream it serves or who comes to visit it. But rather its founder, she stands for something bigger and better. ` 
    }, 
      {
        locationIndex: 10,
        title: "Meet Smitten's Owner",
        location: "Smitten Ice Cream",
        length: 2, 
        date: "May 2019", 
        tags: ["Food", "Community", "Heart-Warmer"], 
        author: "adrazen", 
        image: Images.smittenOwner,
        audio: Audio.smittenOwner,
        transcript: `Smitten Ice Cream is more than just an ice cream shop. Robyn Sue Fisher is a 37-year old founder and proprietor of San Francisco-based Smitten Ice Cream. She’s rethinking ice cream. Ten years ago, Fisher decided she wanted to make being an adult a fun thing so she chased after something she loved--ice cream--and made it better using high tech by taking it back in time, making it pure again, using all natural, local ingredients. It all starts with a story that includes a Stanford MBA, liquid nitrogen, a forty pound machine, bungee-corded to a radio flyer wagon that she hauled around the streets of San Francisco, hoping she wouldn’t get arrested. Listen to this to learn a little bit more about Robyn Sue FIsher and her ice cream shop. `
    },  
      {
        locationIndex: 10,
        title: "My SF Ice Cream Tour",
        location: "Smitten Ice Cream",
        length: 2, 
        date: "May 2019", 
        tags: ["Food"], 
        author: "shinnyshin", 
        image: Images.iceCreamExtravaganza,
        audio: Audio.iceCreamTour,
        transcript: `Some of my favorite times in SF that I can remember was this one time for national ice cream day my friend organized this whole ice cream tour around SF. We visited 4 or 5 ice cream stops. I can’t remember the first one but the other three were Smitten ice cream, which was absolutely delicious, then we went to Loving Cup in SF which is frozen yogurt but it is like Cold Stone version so that was really good. It was really sweet overall, but it was still really delicious. And then the last one we went to was the Baked Bear which was one of my favorites. After we had the ice cream we went right into China Town and Little Italy because it is right in the heart of it. So we were able to have this delicious food and walk around all across SF while having ice cream which is pretty much a perfect day in my opinion. The only downside was there are just so many hills in SF. So we got tired and had to get coffee to sustain us.`,
      }, 
      {
        locationIndex: 10,
        title: "Smitten Founder On Doubling Down At What You’re Good At",
        location: "Smitten Ice Cream",
        length: 40, 
        date: "May 2019", 
        tags: ["Food", "Community", "Women"], 
        author: "willow_older", 
        image: Images.smittenRobyn,
        audio: Audio.smittenRobyn,
        transcript: `Robyn Fisher really loves ice cream. As a kid, she and her family would have ice cream for those special moments in life – to bond, recover and really savor life. Fast forward to college. Robyn was in the middle of her studies and couldn’t find a decent ice cream in NYC. She recalled the fresh gelato she experienced in Italy and realized that while gourmet coffee was taking off, there was a gap in the market for fresh ice cream. This realization set her life path toward the founding of Smitten Ice Cream. After graduating from business school, Robyn found an engineer willing to work for equity for two years on creating a better ice cream machine, Brrr, a liquid nitrogen machine with six patents and a secret formula for gourmet ice cream. This led to the creation of the Today Smitten makes every ice cream batch to order. You read that right – nothing is frozen until the customer orders it. In this episode of I Want Her Job The Podcast, Robyn shares her motivations that led to Smitten and discusses how starting Smitten gave her a life purpose and a job she truly loves. You also will hear Robyn’s unforgettable story of selling her first batch of ice cream in 2009 in a San Francisco park while using a Radio Flyer Wagon attached to a nitrogen machine and motorcycle battery held together with a bungee cord. After spending two years on the idea and her entire savings, Robyn gave herself two weeks to test if there was a market for her product. It was the depth of the recession, but instead of giving up or finding reasons why her idea wouldn't work, Robyn tried her idea on a serious budget, tweeting the location of her Radio Flyer ice cream. Robyn's experiment worked, and people showed up, a lot of people. That experiment changed Robyn's life and showed her there was a market for authentic food made with passion. Today, you can experience Smitten ice cream in five stores in the Bay Area. Beginning in March 2020, wherever you are in the U.S., you will able to give your loved ones the sweetest surprise by making them a unique ice cream flavor. "Spoon me" and "You dumped his ass" are examples of custom ice cream flavors. Robyn's story is the perfect example of having the courage and passion to follow an idea despite the odds or large competitors. Robyn innovated on an existing product, created a unique experience and built a business based on passion, integrity and smiles. If you have dreams of starting your own business, Robyn's story offers plenty inspiration to get you thinking differently about the possibilities.` 
    },  
      {
        locationIndex: 10,
        title: "Learn About Smitten",
        location: "Smitten Ice Cream",
        length: 2, 
        date: "May 2019", 
        tags: ["Food", "Community"], 
        author: "adrazen", 
        image: Images.learnAboutSmitten,
        audio: Audio.learnAboutSmitten,
        transcript: `Let me tell you about Smitten Ice Cream. Robyn Sue Fisher’s affection for ice cream runs through the summer evenings of her Boston childhood, like a swirl of marshmallow cream through a pint of rocky road. “My mom would tell me I had two stomachs: one for food and one totally reserved for ice cream,” she says. While ice cream was Fisher’s family’s dessert of choice almost every night, that didn’t preclude special outings to ice cream shops. Those impromptu visits were filled with happy moments and spending time together, she says. “Building a business around those moments was very attractive to me” she told me about the origins of her ice cream business that recently opened its fifth location in the San Francisco area. Described on its website as “new old-fashioned,” Fisher’s ice cream is made from scratch and to-order from organic milk and cream and other fresh ingredients from local farms.` 
    }, 
];