import { Audio } from '../../Themes';
import {Images} from '../../Themes';
export const sfWharfStories = [
    {
      title: "Fishing Hub to Tourist Mecca",
      length: 22, 
      date: "Jan 2021", 
      tags: ["History", "Community"],
      author: "author",
      transcript: `insert a transcript`,
      image: Images.oasis,
      audio: Audio.oasis,
    },
    {
      title: "San Francisco Maritime History",
      length: 9, 
      date: "Aug 2020", 
      tags: ["History"],
      author: "author",
      transcript: `insert a transcript`,
      image: Images.oasis,
      audio: Audio.oasis,
    },
    {
      title: "Saturday Mornings at the Wharf",
      length: 28, 
      date: "Jul 2020", 
      tags: ["Heart-Warmer", "Community", "Family", "Love"],
      author: "author",
      transcript: `insert a transcript`,
      image: Images.oasis,
      audio: Audio.oasis,
    },
    {
        title: "The Fire at Pier 45",
        length: 33, 
        date: "May 2020", 
        tags: ["Love", "Community", "Heart-Warmer"],
        author: "author",
        transcript: `insert a transcript`,
        image: Images.oasis,
        audio: Audio.oasis,
    },
    {
        title: "Recovering after the Big Fire",
        length: 8, 
        date: "May 2020", 
        tags: ["Community", "Heart-Warmer"],
        author: "author",
        transcript: `insert a transcript`,
        image: Images.oasis,
        audio: Audio.oasis,
    },
    {
        title: "Dawn at the Wharf",
        length: 54, 
        date: "Jan 2020", 
        tags: ["Community"],
        author: "author",
        transcript: `insert a transcript`,
        image: Images.oasis,
        audio: Audio.oasis,
    }
];
